// Generated by ffigen from native/include/alexandria_ffi.h — do not edit.
// See IR-03 in docs/requirements/Operations & Infrastructure Document.md.
//
// ignore_for_file: type=lint, unused_field, camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Generated bindings over the Alexandria core's C ABI.
///
/// DO NOT EDIT. Generated from native/include/alexandria_ffi.h by ffigen.
///
class AlexandriaBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AlexandriaBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AlexandriaBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Local login (UC-34 / FR-AU-04): verify email + password and create a
  /// session. `json_body` is the JSON body HTTP would send (`email`,
  /// `password`). On success `json` carries the `LocalLoginResult` — the
  /// caller presents its `sessionId` on subsequent requests instead of a
  /// bearer token in local mode.
  ///
  /// Deliberately takes no `token`: this is how a caller obtains credentials
  /// in the first place (mirrors the HTTP route being outside the auth gate).
  AuthJsonResult alexandria_auth_local_login(ffi.Pointer<ffi.Char> json_body) {
    return _alexandria_auth_local_login(json_body);
  }

  late final _alexandria_auth_local_loginPtr =
      _lookup<
        ffi.NativeFunction<AuthJsonResult Function(ffi.Pointer<ffi.Char>)>
      >('alexandria_auth_local_login');
  late final _alexandria_auth_local_login = _alexandria_auth_local_loginPtr
      .asFunction<AuthJsonResult Function(ffi.Pointer<ffi.Char>)>();

  /// Register the local account (UC-41 / FR-AU-10, FR-AU-11): create the
  /// single owner's credentials and open a session. `json_body` is the JSON
  /// body HTTP would send (`email`, `password`, `passwordConfirmation`). On
  /// success `json` carries the `LocalRegisterResult`, whose `sessionId` the
  /// caller presents on subsequent requests.
  ///
  /// Deliberately takes no `token`: there is nothing to authenticate with
  /// before an account exists. Succeeds only once — a second call returns
  /// `AUTH_ERR_CONFLICT` (AF-02).
  AuthJsonResult alexandria_auth_local_register(
    ffi.Pointer<ffi.Char> json_body,
  ) {
    return _alexandria_auth_local_register(json_body);
  }

  late final _alexandria_auth_local_registerPtr =
      _lookup<
        ffi.NativeFunction<AuthJsonResult Function(ffi.Pointer<ffi.Char>)>
      >('alexandria_auth_local_register');
  late final _alexandria_auth_local_register =
      _alexandria_auth_local_registerPtr
          .asFunction<AuthJsonResult Function(ffi.Pointer<ffi.Char>)>();

  /// Set or change local-login credentials (UC-35 / FR-AU-05, FR-AU-06).
  /// `json_body` is the JSON body HTTP would send (`email`, `password`).
  /// `token` is required: this changes existing credentials. Creating the
  /// account is `alexandria_auth_local_register` (UC-41).
  AuthJsonResult alexandria_auth_local_set_credentials(
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_auth_local_set_credentials(json_body, token);
  }

  late final _alexandria_auth_local_set_credentialsPtr =
      _lookup<
        ffi.NativeFunction<
          AuthJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_auth_local_set_credentials');
  late final _alexandria_auth_local_set_credentials =
      _alexandria_auth_local_set_credentialsPtr
          .asFunction<
            AuthJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Create a browser bookmark, optionally in an existing bookmark collection
  /// (UC-15 / FR-BM-01).
  ///
  /// `json_body` is the JSON body HTTP would send (`url` + `title` +
  /// `collectionUuid`). The function deserializes it, calls the same
  /// `CreateBookmarkHandler` the HTTP route uses, and on success serializes the
  /// returned `Bookmark` back to JSON — so the FFI and HTTP surfaces agree
  /// byte-for-byte modulo key ordering (parity, FR-FC-24 / NFR-09). `token` is
  /// the bearer auth token.
  BookmarkJsonResult alexandria_bookmark_create(
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_bookmark_create(json_body, token);
  }

  late final _alexandria_bookmark_createPtr =
      _lookup<
        ffi.NativeFunction<
          BookmarkJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_bookmark_create');
  late final _alexandria_bookmark_create = _alexandria_bookmark_createPtr
      .asFunction<
        BookmarkJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Hard-purge a bookmark (UC-19 / FR-BM-04).
  ///
  /// `uuid` is the bookmark's public UUID (NUL-terminated string). On success
  /// `json` carries the pre-purge `Bookmark` as confirmation — byte-for-byte
  /// the same shape HTTP returns from `DELETE /v1/bookmarks/{uuid}?purge=true`
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  BookmarkJsonResult alexandria_bookmark_purge(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_bookmark_purge(uuid, token);
  }

  late final _alexandria_bookmark_purgePtr =
      _lookup<
        ffi.NativeFunction<
          BookmarkJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_bookmark_purge');
  late final _alexandria_bookmark_purge = _alexandria_bookmark_purgePtr
      .asFunction<
        BookmarkJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Restore a soft-deleted bookmark (UC-18 / FR-BM-05).
  ///
  /// `uuid` is the bookmark's public UUID (NUL-terminated string). On success
  /// `json` carries the restored `Bookmark` — byte-for-byte the same shape
  /// HTTP returns from `POST /v1/bookmarks/{uuid}/restore` (parity,
  /// FR-FC-24 / NFR-09). `token` is the bearer auth token.
  BookmarkJsonResult alexandria_bookmark_restore(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_bookmark_restore(uuid, token);
  }

  late final _alexandria_bookmark_restorePtr =
      _lookup<
        ffi.NativeFunction<
          BookmarkJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_bookmark_restore');
  late final _alexandria_bookmark_restore = _alexandria_bookmark_restorePtr
      .asFunction<
        BookmarkJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Soft-delete a bookmark (UC-18 / FR-BM-03).
  ///
  /// `uuid` is the bookmark's public UUID (NUL-terminated string). On success
  /// `json` carries the updated `Bookmark` — byte-for-byte the same shape HTTP
  /// returns from `DELETE /v1/bookmarks/{uuid}` (parity, FR-FC-24 / NFR-09).
  /// `token` is the bearer auth token.
  BookmarkJsonResult alexandria_bookmark_soft_delete(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_bookmark_soft_delete(uuid, token);
  }

  late final _alexandria_bookmark_soft_deletePtr =
      _lookup<
        ffi.NativeFunction<
          BookmarkJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_bookmark_soft_delete');
  late final _alexandria_bookmark_soft_delete =
      _alexandria_bookmark_soft_deletePtr
          .asFunction<
            BookmarkJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Update a bookmark's url, title, and containing collection (UC-16 /
  /// FR-BM-02).
  ///
  /// `uuid` is the bookmark's public UUID (NUL-terminated string). `json_body`
  /// is the JSON body HTTP would send (`url` + `title` + `collectionUuid`).
  /// The function deserializes it, calls the same `UpdateBookmarkHandler` the
  /// HTTP route uses, and on success serializes the returned `Bookmark` back
  /// to JSON — so the FFI and HTTP surfaces agree byte-for-byte modulo key
  /// ordering (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  BookmarkJsonResult alexandria_bookmark_update(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_bookmark_update(uuid, json_body, token);
  }

  late final _alexandria_bookmark_updatePtr =
      _lookup<
        ffi.NativeFunction<
          BookmarkJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_bookmark_update');
  late final _alexandria_bookmark_update = _alexandria_bookmark_updatePtr
      .asFunction<
        BookmarkJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Browse bookmarks, optionally filtered by containing collection (UC-17 /
  /// FR-BM-06).
  ///
  /// `json_filters` is a JSON string `{"collectionUuid":"…","state":"all"}`
  /// (empty string or NULL for defaults). The function deserializes it, calls
  /// the same `BrowseBookmarksHandler` the HTTP route uses, and on success
  /// serializes the returned `Vec<Bookmark>` back to a JSON array — so the FFI
  /// and HTTP surfaces agree byte-for-byte modulo key ordering (parity,
  /// FR-FC-24 / NFR-09). `token` is the bearer auth token.
  BookmarkJsonResult alexandria_bookmarks_list(
    ffi.Pointer<ffi.Char> json_filters,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_bookmarks_list(json_filters, token);
  }

  late final _alexandria_bookmarks_listPtr =
      _lookup<
        ffi.NativeFunction<
          BookmarkJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_bookmarks_list');
  late final _alexandria_bookmarks_list = _alexandria_bookmarks_listPtr
      .asFunction<
        BookmarkJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Add items to a collection (UC-13 / FR-CO-05).
  ///
  /// `uuid` is the collection's public UUID (NUL-terminated string). `json_body`
  /// is the JSON body HTTP would send (`itemUuids`). The function deserializes
  /// it, calls the same `AddItemsToCollectionHandler` the HTTP route uses, and
  /// on success serializes the returned `CollectionItemsResult` back to JSON —
  /// so the FFI and HTTP surfaces agree byte-for-byte modulo key ordering
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  CollectionJsonResult alexandria_collection_add_items(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_collection_add_items(uuid, json_body, token);
  }

  late final _alexandria_collection_add_itemsPtr =
      _lookup<
        ffi.NativeFunction<
          CollectionJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_collection_add_items');
  late final _alexandria_collection_add_items =
      _alexandria_collection_add_itemsPtr
          .asFunction<
            CollectionJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Create a flat file or bookmark collection (UC-10 / FR-CO-01, FR-CO-02).
  ///
  /// `json_body` is the JSON body HTTP would send (`name` + `kind`). The
  /// function deserializes it, calls the same `CreateCollectionHandler` the HTTP
  /// route uses, and on success serializes the returned `Collection` back to
  /// JSON — so the FFI and HTTP surfaces agree byte-for-byte modulo key ordering
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  CollectionJsonResult alexandria_collection_create(
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_collection_create(json_body, token);
  }

  late final _alexandria_collection_createPtr =
      _lookup<
        ffi.NativeFunction<
          CollectionJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_collection_create');
  late final _alexandria_collection_create = _alexandria_collection_createPtr
      .asFunction<
        CollectionJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Delete a collection, unlinking its items (UC-12 / FR-CO-04).
  ///
  /// `uuid` is the collection's public UUID (NUL-terminated string). On success
  /// `json` carries the pre-delete `Collection` as confirmation — byte-for-byte
  /// the same shape HTTP returns from `DELETE /v1/collections/{uuid}` (parity,
  /// FR-FC-24 / NFR-09). `token` is the bearer auth token.
  CollectionJsonResult alexandria_collection_delete(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_collection_delete(uuid, token);
  }

  late final _alexandria_collection_deletePtr =
      _lookup<
        ffi.NativeFunction<
          CollectionJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_collection_delete');
  late final _alexandria_collection_delete = _alexandria_collection_deletePtr
      .asFunction<
        CollectionJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// List the items in a collection (UC-14 / FR-CO-07).
  ///
  /// `uuid` is the collection's public UUID (NUL-terminated string). On
  /// success `json` carries the `kind` and current members — byte-for-byte
  /// the same shape HTTP returns from `GET /v1/collections/{uuid}/items`
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  CollectionJsonResult alexandria_collection_list_items(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_collection_list_items(uuid, token);
  }

  late final _alexandria_collection_list_itemsPtr =
      _lookup<
        ffi.NativeFunction<
          CollectionJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_collection_list_items');
  late final _alexandria_collection_list_items =
      _alexandria_collection_list_itemsPtr
          .asFunction<
            CollectionJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Remove an item from a collection (UC-14 / FR-CO-06).
  ///
  /// `collection_uuid` and `item_uuid` are the collection's and item's public
  /// UUIDs (NUL-terminated strings). On success `json` carries the
  /// `collectionUuid`/`itemUuid` confirmation — byte-for-byte the same shape
  /// HTTP returns from `DELETE /v1/collections/{uuid}/items/{itemUuid}`
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  CollectionJsonResult alexandria_collection_remove_item(
    ffi.Pointer<ffi.Char> collection_uuid,
    ffi.Pointer<ffi.Char> item_uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_collection_remove_item(
      collection_uuid,
      item_uuid,
      token,
    );
  }

  late final _alexandria_collection_remove_itemPtr =
      _lookup<
        ffi.NativeFunction<
          CollectionJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_collection_remove_item');
  late final _alexandria_collection_remove_item =
      _alexandria_collection_remove_itemPtr
          .asFunction<
            CollectionJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Rename a collection (UC-11 / FR-CO-03).
  ///
  /// `uuid` is the collection's public UUID (NUL-terminated string). `json_body`
  /// is the JSON body HTTP would send (`{"name": …}`). The function
  /// deserializes it, calls the same `RenameCollectionHandler` the HTTP route
  /// uses, and on success serializes the returned `Collection` back to JSON —
  /// so the FFI and HTTP surfaces agree byte-for-byte modulo key ordering
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  CollectionJsonResult alexandria_collection_rename(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_collection_rename(uuid, json_body, token);
  }

  late final _alexandria_collection_renamePtr =
      _lookup<
        ffi.NativeFunction<
          CollectionJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_collection_rename');
  late final _alexandria_collection_rename = _alexandria_collection_renamePtr
      .asFunction<
        CollectionJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// One page of a CBZ ComicBook (UC-39 / FR-MP-04).
  ///
  /// Returns `{"uuid":…,"page":N,"pageCount":N,"mimeType":…,"bytesBase64":…}`.
  /// Unlike UC-38, the bytes *do* cross the boundary: a comic page has no path
  /// of its own — it lives inside an archive — and it is bounded, so
  /// base64 inside the existing JSON payload keeps the FFI shape intact while
  /// staying byte-exact with HTTP.
  PlaybackJsonResult alexandria_comic_page(
    ffi.Pointer<ffi.Char> uuid,
    int page,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_comic_page(uuid, page, token);
  }

  late final _alexandria_comic_pagePtr =
      _lookup<
        ffi.NativeFunction<
          PlaybackJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Uint32,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_comic_page');
  late final _alexandria_comic_page = _alexandria_comic_pagePtr
      .asFunction<
        PlaybackJsonResult Function(
          ffi.Pointer<ffi.Char>,
          int,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Write edited content back to a TextFile on disk (UC-33 / FR-TX-02,
  /// FR-TX-03).
  ///
  /// `uuid` is the file's public UUID (NUL-terminated string). `json_body` is
  /// the JSON body HTTP would send (`content`). The function deserializes it,
  /// calls the same `EditTextFileContentHandler` the HTTP route uses, and on
  /// success serializes the returned `File` back to JSON — so the FFI and
  /// HTTP surfaces agree byte-for-byte modulo key ordering (parity,
  /// FR-FC-24 / NFR-09). `token` is the bearer auth token.
  FileJsonResult alexandria_file_edit_content(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_edit_content(uuid, json_body, token);
  }

  late final _alexandria_file_edit_contentPtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_file_edit_content');
  late final _alexandria_file_edit_content = _alexandria_file_edit_contentPtr
      .asFunction<
        FileJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Edit a file's type-specific metadata (UC-04 / FR-FC-14..18).
  ///
  /// `uuid` is the file's public UUID string; `json_patch` is the JSON body
  /// (the `SubtypeMetadata` enum, internally tagged by `type`) that HTTP would
  /// send. The function deserializes it, calls the same `EditMetadataHandler`
  /// the HTTP route uses, and on success serializes the returned `FileMetadata`
  /// back to JSON — so the FFI and HTTP surfaces agree byte-for-byte modulo key
  /// ordering (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  FileMetadataResult alexandria_file_edit_metadata(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> json_patch,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_edit_metadata(uuid, json_patch, token);
  }

  late final _alexandria_file_edit_metadataPtr =
      _lookup<
        ffi.NativeFunction<
          FileMetadataResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_file_edit_metadata');
  late final _alexandria_file_edit_metadata = _alexandria_file_edit_metadataPtr
      .asFunction<
        FileMetadataResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Get a single file's metadata by its public UUID (UC-03 / FR-FC-13).
  ///
  /// `uuid` is the file's public UUID string. The function calls the same
  /// `BrowseFilesHandler::get_by_uuid` the HTTP route uses, and on success
  /// serializes the returned `FileView` back to JSON — the same shape HTTP
  /// returns from `GET /v1/files/{uuid}` (parity, FR-FC-24 / NFR-09). `token`
  /// is the bearer auth token.
  FileJsonResult alexandria_file_get_by_uuid(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_get_by_uuid(uuid, token);
  }

  late final _alexandria_file_get_by_uuidPtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_file_get_by_uuid');
  late final _alexandria_file_get_by_uuid = _alexandria_file_get_by_uuidPtr
      .asFunction<
        FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// Resolve a File to everything a local player needs to open it
  /// (UC-38 / FR-MP-01, FR-MP-06).
  ///
  /// The FFI surface cannot carry a byte stream, so where HTTP streams
  /// `GET /v1/files/{uuid}/stream`, this returns
  /// `{"uuid":…,"path":…,"mimeType":…,"sizeBytes":…}` and the caller — Flutter
  /// desktop, on the same machine as the file — opens that path directly.
  /// Zero bytes cross this boundary. Parity with HTTP is defined on this
  /// descriptor and on the authorization, state, and error decisions rather
  /// than on byte transfer (FR-MP-06).
  PlaybackJsonResult alexandria_file_playback_source(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_playback_source(uuid, token);
  }

  late final _alexandria_file_playback_sourcePtr =
      _lookup<
        ffi.NativeFunction<
          PlaybackJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_file_playback_source');
  late final _alexandria_file_playback_source =
      _alexandria_file_playback_sourcePtr
          .asFunction<
            PlaybackJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Hard-purge a soft-deleted file's catalog row (UC-08 / FR-FC-22).
  ///
  /// `uuid` is the file's public UUID string; `token` is the bearer auth
  /// token. The function calls the same `PurgeFileHandler` the HTTP route
  /// uses (`DELETE /v1/files/{uuid}?purge=true`) and on success serializes
  /// the pre-delete `File` back to JSON as confirmation — the same shape
  /// HTTP returns, so the FFI and HTTP surfaces agree byte-for-byte modulo
  /// key ordering (parity, FR-FC-24 / NFR-09). Only the catalog row (and its
  /// subtype row) is removed; the on-disk file is untouched (NFR-07). The
  /// retention window (default 30 days, NFR-10) is enforced: a record still
  /// within it, or not `deleted`, is reported as `FILE_ERR_INVALID_STATE`.
  FileJsonResult alexandria_file_purge(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_purge(uuid, token);
  }

  late final _alexandria_file_purgePtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_file_purge');
  late final _alexandria_file_purge = _alexandria_file_purgePtr
      .asFunction<
        FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// Purge a file both on disk and in the catalog (UC-09 / FR-FC-23).
  ///
  /// `uuid` is the file's public UUID string; `token` is the bearer auth
  /// token. The function calls the same `PurgeFileOnDiskHandler` the HTTP
  /// route uses (`DELETE /v1/files/{uuid}?purge-on-disk=true`) and on success
  /// serializes the returned [`PurgeOnDiskOutcome`] back to JSON — the same
  /// shape HTTP returns, so the FFI and HTTP surfaces agree byte-for-byte
  /// modulo key ordering (parity, FR-FC-24 / NFR-09). Unlike UC-08 there is no
  /// retention gate: an `active` or `deleted` record is purgeable, the only
  /// precondition is that it exists. A missing on-disk file is still a
  /// success, reported via `diskFilePresent: false` (AF-01); a disk failure
  /// is reported as `FILE_ERR_DISK` (AF-02) and leaves the record untouched.
  FileJsonResult alexandria_file_purge_on_disk(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_purge_on_disk(uuid, token);
  }

  late final _alexandria_file_purge_on_diskPtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_file_purge_on_disk');
  late final _alexandria_file_purge_on_disk = _alexandria_file_purge_on_diskPtr
      .asFunction<
        FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// Read a TextFile's content from disk (UC-32 / FR-TX-01).
  ///
  /// `uuid` is the file's public UUID (NUL-terminated string). On success
  /// `json` carries the `FileContent` — byte-for-byte the same shape HTTP
  /// returns from `GET /v1/files/{uuid}/content` (parity, FR-FC-24 / NFR-09).
  /// `token` is the bearer auth token.
  FileJsonResult alexandria_file_read_content(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_read_content(uuid, token);
  }

  late final _alexandria_file_read_contentPtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_file_read_content');
  late final _alexandria_file_read_content = _alexandria_file_read_contentPtr
      .asFunction<
        FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// Rename a file (and its on-disk file) (UC-05 / FR-FC-19).
  ///
  /// `uuid` is the file's public UUID string; `name` is the new file name. The
  /// function calls the same `RenameFileHandler` the HTTP route uses and on
  /// success serializes the returned `File` back to JSON — the same shape HTTP
  /// returns from `POST /v1/files/{uuid}/rename`, so the FFI and HTTP surfaces
  /// agree byte-for-byte modulo key ordering (parity, FR-FC-24 / NFR-09).
  /// `token` is the bearer auth token. A disk failure (AF-02) maps to
  /// `FILE_ERR_DISK`; the catalog is left untouched in that case.
  FileJsonResult alexandria_file_rename(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> name,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_rename(uuid, name, token);
  }

  late final _alexandria_file_renamePtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_file_rename');
  late final _alexandria_file_rename = _alexandria_file_renamePtr
      .asFunction<
        FileJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Restore a soft-deleted file (UC-07 / FR-FC-21).
  ///
  /// `uuid` is the file's public UUID string; `token` is the bearer auth token.
  /// The function calls the same `RestoreFileHandler` the HTTP route uses and
  /// on success serializes the returned `File` back to JSON — the same shape
  /// HTTP returns from `POST /v1/files/{uuid}/restore`, so the FFI and HTTP
  /// surfaces agree byte-for-byte modulo key ordering (parity, FR-FC-24 /
  /// NFR-09). The on-disk file is untouched (only `state` and `deleted_at`
  /// change on the catalog row). The retention window (default 30 days,
  /// NFR-10) is enforced; a record past it is reported as `NotFound`
  /// (`FILE_ERR_NOT_FOUND`) since UC-08 owns the actual hard purge.
  FileJsonResult alexandria_file_restore(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_restore(uuid, token);
  }

  late final _alexandria_file_restorePtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_file_restore');
  late final _alexandria_file_restore = _alexandria_file_restorePtr
      .asFunction<
        FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// Soft-delete a file (UC-06 / FR-FC-20).
  ///
  /// `uuid` is the file's public UUID string; `token` is the bearer auth token.
  /// The function calls the same `SoftDeleteFileHandler` the HTTP route uses
  /// and on success serializes the returned `File` back to JSON — the same
  /// shape HTTP returns from `DELETE /v1/files/{uuid}`, so the FFI and HTTP
  /// surfaces agree byte-for-byte modulo key ordering (parity, FR-FC-24 /
  /// NFR-09). The on-disk file is untouched (only `state` and `deleted_at`
  /// change on the catalog row).
  FileJsonResult alexandria_file_soft_delete(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_soft_delete(uuid, token);
  }

  late final _alexandria_file_soft_deletePtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_file_soft_delete');
  late final _alexandria_file_soft_delete = _alexandria_file_soft_deletePtr
      .asFunction<
        FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// A downscaled thumbnail for a video, image, or comic
  /// (UC-40 / FR-MP-05). Returns
  /// `{"uuid":…,"mimeType":"image/jpeg","bytesBase64":…}`. Bounded derived
  /// bytes, so the same base64 rule as `alexandria_comic_page` applies.
  PlaybackJsonResult alexandria_file_thumbnail(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_file_thumbnail(uuid, token);
  }

  late final _alexandria_file_thumbnailPtr =
      _lookup<
        ffi.NativeFunction<
          PlaybackJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_file_thumbnail');
  late final _alexandria_file_thumbnail = _alexandria_file_thumbnailPtr
      .asFunction<
        PlaybackJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// List/query files filtered by type and lifecycle state (UC-03 / FR-FC-12).
  ///
  /// `json_filters` is a JSON string `{"type":"audio","state":"all"}` (empty
  /// string or NULL for defaults). The function deserializes it, calls the same
  /// `BrowseFilesHandler` the HTTP route uses, and on success serializes the
  /// returned `Vec<File>` back to a JSON array — so the FFI and HTTP surfaces
  /// agree byte-for-byte modulo key ordering (parity, FR-FC-24 / NFR-09).
  /// `token` is the bearer auth token.
  FileJsonResult alexandria_files_list(
    ffi.Pointer<ffi.Char> json_filters,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_files_list(json_filters, token);
  }

  late final _alexandria_files_listPtr =
      _lookup<
        ffi.NativeFunction<
          FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_files_list');
  late final _alexandria_files_list = _alexandria_files_listPtr
      .asFunction<
        FileJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// Free a string previously returned by an FFI accessor.
  ///
  /// # Safety
  ///
  /// `ptr` must be null, or a pointer returned by one of this library's
  /// accessors and not yet freed. Passing anything else — a pointer this library
  /// did not produce, or one already freed — is undefined behaviour. Declared
  /// `unsafe` because that obligation is the caller's and cannot be checked here.
  void alexandria_free_string(ffi.Pointer<ffi.Char> ptr) {
    return _alexandria_free_string(ptr);
  }

  late final _alexandria_free_stringPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'alexandria_free_string',
      );
  late final _alexandria_free_string = _alexandria_free_stringPtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  int alexandria_health_status_code() {
    return _alexandria_health_status_code();
  }

  late final _alexandria_health_status_codePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>(
        'alexandria_health_status_code',
      );
  late final _alexandria_health_status_code = _alexandria_health_status_codePtr
      .asFunction<int Function()>();

  /// Count of indexed files. For tests waiting for the background scan.
  int alexandria_index_count_files() {
    return _alexandria_index_count_files();
  }

  late final _alexandria_index_count_filesPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'alexandria_index_count_files',
      );
  late final _alexandria_index_count_files = _alexandria_index_count_filesPtr
      .asFunction<int Function()>();

  /// Count of cataloged files currently marked missing on disk (UC-02 AF-01).
  int alexandria_index_count_missing() {
    return _alexandria_index_count_missing();
  }

  late final _alexandria_index_count_missingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'alexandria_index_count_missing',
      );
  late final _alexandria_index_count_missing =
      _alexandria_index_count_missingPtr.asFunction<int Function()>();

  /// JSON array of `{"path","name","type","hash"}` for every indexed file, or a
  /// NUL pointer on error. Caller must free it with `alexandria_free_string`.
  ffi.Pointer<ffi.Char> alexandria_index_files_json() {
    return _alexandria_index_files_json();
  }

  late final _alexandria_index_files_jsonPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'alexandria_index_files_json',
      );
  late final _alexandria_index_files_json = _alexandria_index_files_jsonPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Initialize the FFI services against a database path (created/migrated on
  /// demand). Safe to call again to point at a different database (replaces).
  /// Returns 0 on success, a non-zero status otherwise.
  ///
  /// Configuration is loaded the same way `alexandria-http` loads it — from the
  /// path in `ALEXANDRIA_CONFIG` (default `config.toml`), with `ALEXANDRIA_*`
  /// environment overrides applied — so a setting such as the auth mode or the
  /// retention window means the same thing on both surfaces (FR-FC-24 / NFR-09).
  /// A missing or unreadable config file falls back to defaults rather than
  /// failing, matching the HTTP binary. `db_path` wins over the config's
  /// `database.path`: the embedder passed it explicitly.
  int alexandria_index_init(ffi.Pointer<ffi.Char> db_path) {
    return _alexandria_index_init(db_path);
  }

  late final _alexandria_index_initPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'alexandria_index_init',
      );
  late final _alexandria_index_init = _alexandria_index_initPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Start an asynchronous re-index/refresh of every cataloged path (UC-02).
  /// Takes only a token (no root — refresh touches everything cataloged) and
  /// returns a `IndexStartResult` with a `run_id` and `status` (parity with the
  /// HTTP `POST /v1/index/refresh` 202 body). The refresh runs in the background
  /// on the FFI runtime; read results via the accessor functions.
  IndexStartResult alexandria_index_refresh_start(ffi.Pointer<ffi.Char> token) {
    return _alexandria_index_refresh_start(token);
  }

  late final _alexandria_index_refresh_startPtr =
      _lookup<
        ffi.NativeFunction<IndexStartResult Function(ffi.Pointer<ffi.Char>)>
      >('alexandria_index_refresh_start');
  late final _alexandria_index_refresh_start =
      _alexandria_index_refresh_startPtr
          .asFunction<IndexStartResult Function(ffi.Pointer<ffi.Char>)>();

  /// Report an index or re-index run's status and outcome (UC-42 / FR-FC-28).
  /// `run_id` is the id `alexandria_index_start` or
  /// `alexandria_index_refresh_start` returned. On success `json` carries the
  /// same body the HTTP `GET /v1/index/runs/{runId}` route returns (FR-FC-24).
  ///
  /// Returns `RUN_ERR_NOT_FOUND` for an id naming no run (AF-01),
  /// `RUN_ERR_UNAUTHORIZED` for an unauthenticated caller (AF-02), and
  /// `RUN_ERR_INVALID_INPUT` when `run_id` is not a uuid.
  RunJsonResult alexandria_index_run_status_json(
    ffi.Pointer<ffi.Char> run_id,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_index_run_status_json(run_id, token);
  }

  late final _alexandria_index_run_status_jsonPtr =
      _lookup<
        ffi.NativeFunction<
          RunJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
        >
      >('alexandria_index_run_status_json');
  late final _alexandria_index_run_status_json =
      _alexandria_index_run_status_jsonPtr
          .asFunction<
            RunJsonResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
          >();

  /// Start an asynchronous index scan of `root`. Returns a `IndexStartResult`
  /// with a `run_id` and `status` (parity with HTTP 202 body). The scan runs in
  /// the background on the FFI runtime; read results via the accessor functions.
  IndexStartResult alexandria_index_start(
    ffi.Pointer<ffi.Char> root,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_index_start(root, token);
  }

  late final _alexandria_index_startPtr =
      _lookup<
        ffi.NativeFunction<
          IndexStartResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_index_start');
  late final _alexandria_index_start = _alexandria_index_startPtr
      .asFunction<
        IndexStartResult Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      >();

  /// Add a book or comic to a reading list (UC-28 / FR-RL-02, FR-RL-03).
  ///
  /// `uuid` is the reading list's public UUID (NUL-terminated string).
  /// `json_body` is the JSON body HTTP would send (`itemUuid`). The function
  /// deserializes it, calls the same `AddItemToReadingListHandler` the HTTP
  /// route uses, and on success serializes the returned `ReadingProgress`
  /// back to JSON — so the FFI and HTTP surfaces agree byte-for-byte modulo
  /// key ordering (parity, FR-FC-24 / NFR-09). `token` is the bearer auth
  /// token.
  ReadingListJsonResult alexandria_reading_list_add_item(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_reading_list_add_item(uuid, json_body, token);
  }

  late final _alexandria_reading_list_add_itemPtr =
      _lookup<
        ffi.NativeFunction<
          ReadingListJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_reading_list_add_item');
  late final _alexandria_reading_list_add_item =
      _alexandria_reading_list_add_itemPtr
          .asFunction<
            ReadingListJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Create a named reading list for tracking book/comic consumption (UC-26 /
  /// FR-RL-01).
  ///
  /// `json_body` is the JSON body HTTP would send (`name`). The function
  /// deserializes it, calls the same `CreateReadingListHandler` the HTTP
  /// route uses, and on success serializes the returned `ReadingList` back to
  /// JSON — so the FFI and HTTP surfaces agree byte-for-byte modulo key
  /// ordering (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  ReadingListJsonResult alexandria_reading_list_create(
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_reading_list_create(json_body, token);
  }

  late final _alexandria_reading_list_createPtr =
      _lookup<
        ffi.NativeFunction<
          ReadingListJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_reading_list_create');
  late final _alexandria_reading_list_create =
      _alexandria_reading_list_createPtr
          .asFunction<
            ReadingListJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Delete a reading list (UC-31 / FR-RL-07).
  ///
  /// `uuid` is the reading list's public UUID (NUL-terminated string). On
  /// success `json` carries the pre-delete `ReadingList` — byte-for-byte the
  /// same shape HTTP returns from `DELETE /v1/reading-lists/{uuid}` (parity,
  /// FR-FC-24 / NFR-09). `token` is the bearer auth token.
  ReadingListJsonResult alexandria_reading_list_delete(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_reading_list_delete(uuid, token);
  }

  late final _alexandria_reading_list_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ReadingListJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_reading_list_delete');
  late final _alexandria_reading_list_delete =
      _alexandria_reading_list_deletePtr
          .asFunction<
            ReadingListJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Remove an item from a reading list (UC-30 / FR-RL-06).
  ///
  /// `reading_list_uuid` and `item_uuid` are the reading list's and item's
  /// public UUIDs (NUL-terminated strings). On success `json` carries the
  /// `readingListUuid`/`itemUuid` confirmation — byte-for-byte the same shape
  /// HTTP returns from `DELETE /v1/reading-lists/{uuid}/items/{itemUuid}`
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  ReadingListJsonResult alexandria_reading_list_remove_item(
    ffi.Pointer<ffi.Char> reading_list_uuid,
    ffi.Pointer<ffi.Char> item_uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_reading_list_remove_item(
      reading_list_uuid,
      item_uuid,
      token,
    );
  }

  late final _alexandria_reading_list_remove_itemPtr =
      _lookup<
        ffi.NativeFunction<
          ReadingListJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_reading_list_remove_item');
  late final _alexandria_reading_list_remove_item =
      _alexandria_reading_list_remove_itemPtr
          .asFunction<
            ReadingListJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Update reading progress (UC-29 / FR-RL-04, FR-RL-05).
  ///
  /// `reading_list_uuid` and `item_uuid` are the reading list's and item's
  /// public UUIDs (NUL-terminated strings). `json_body` is the JSON body HTTP
  /// would send (`state`, optional `currentIssue`/`totalIssues`). On success
  /// `json` carries the updated `ReadingProgress` — byte-for-byte the same
  /// shape HTTP returns from `PATCH /v1/reading-lists/{uuid}/items/{itemUuid}`
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  ReadingListJsonResult alexandria_reading_list_update_progress(
    ffi.Pointer<ffi.Char> reading_list_uuid,
    ffi.Pointer<ffi.Char> item_uuid,
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_reading_list_update_progress(
      reading_list_uuid,
      item_uuid,
      json_body,
      token,
    );
  }

  late final _alexandria_reading_list_update_progressPtr =
      _lookup<
        ffi.NativeFunction<
          ReadingListJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_reading_list_update_progress');
  late final _alexandria_reading_list_update_progress =
      _alexandria_reading_list_update_progressPtr
          .asFunction<
            ReadingListJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Browse reading lists and their items' read progress (UC-27 / FR-RL-08).
  ///
  /// `json_filters` is the JSON filter HTTP would build from its query string
  /// (`readingListUuid`); an empty string or `null` means every reading list.
  /// On success `json` carries a JSON array of `ReadingListWithProgress` —
  /// byte-for-byte the same shape HTTP returns from `GET /v1/reading-lists`
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  ReadingListJsonResult alexandria_reading_lists_list(
    ffi.Pointer<ffi.Char> json_filters,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_reading_lists_list(json_filters, token);
  }

  late final _alexandria_reading_lists_listPtr =
      _lookup<
        ffi.NativeFunction<
          ReadingListJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_reading_lists_list');
  late final _alexandria_reading_lists_list = _alexandria_reading_lists_listPtr
      .asFunction<
        ReadingListJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  ffi.Pointer<ffi.Char> alexandria_version() {
    return _alexandria_version();
  }

  late final _alexandria_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'alexandria_version',
      );
  late final _alexandria_version = _alexandria_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Add a video to a watchlist (UC-22 / FR-WL-02, FR-WL-03).
  ///
  /// `uuid` is the watchlist's public UUID (NUL-terminated string). `json_body`
  /// is the JSON body HTTP would send (`videoUuid`). The function deserializes
  /// it, calls the same `AddVideoToWatchlistHandler` the HTTP route uses, and
  /// on success serializes the returned `WatchProgress` back to JSON — so the
  /// FFI and HTTP surfaces agree byte-for-byte modulo key ordering (parity,
  /// FR-FC-24 / NFR-09). `token` is the bearer auth token.
  WatchlistJsonResult alexandria_watchlist_add_video(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_watchlist_add_video(uuid, json_body, token);
  }

  late final _alexandria_watchlist_add_videoPtr =
      _lookup<
        ffi.NativeFunction<
          WatchlistJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_watchlist_add_video');
  late final _alexandria_watchlist_add_video =
      _alexandria_watchlist_add_videoPtr
          .asFunction<
            WatchlistJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Create a named watchlist for tracking video consumption (UC-20 /
  /// FR-WL-01).
  ///
  /// `json_body` is the JSON body HTTP would send (`name`). The function
  /// deserializes it, calls the same `CreateWatchlistHandler` the HTTP route
  /// uses, and on success serializes the returned `Watchlist` back to JSON —
  /// so the FFI and HTTP surfaces agree byte-for-byte modulo key ordering
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  WatchlistJsonResult alexandria_watchlist_create(
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_watchlist_create(json_body, token);
  }

  late final _alexandria_watchlist_createPtr =
      _lookup<
        ffi.NativeFunction<
          WatchlistJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_watchlist_create');
  late final _alexandria_watchlist_create = _alexandria_watchlist_createPtr
      .asFunction<
        WatchlistJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Delete a watchlist (UC-25 / FR-WL-07).
  ///
  /// `uuid` is the watchlist's public UUID (NUL-terminated string). On success
  /// `json` carries the pre-delete `Watchlist` — byte-for-byte the same shape
  /// HTTP returns from `DELETE /v1/watchlists/{uuid}` (parity, FR-FC-24 /
  /// NFR-09). `token` is the bearer auth token.
  WatchlistJsonResult alexandria_watchlist_delete(
    ffi.Pointer<ffi.Char> uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_watchlist_delete(uuid, token);
  }

  late final _alexandria_watchlist_deletePtr =
      _lookup<
        ffi.NativeFunction<
          WatchlistJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_watchlist_delete');
  late final _alexandria_watchlist_delete = _alexandria_watchlist_deletePtr
      .asFunction<
        WatchlistJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// Remove a video from a watchlist (UC-24 / FR-WL-06).
  ///
  /// `watchlist_uuid` and `video_uuid` are the watchlist's and video's public
  /// UUIDs (NUL-terminated strings). On success `json` carries the
  /// `watchlistUuid`/`videoUuid` confirmation — byte-for-byte the same shape
  /// HTTP returns from `DELETE /v1/watchlists/{uuid}/items/{videoUuid}`
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  WatchlistJsonResult alexandria_watchlist_remove_video(
    ffi.Pointer<ffi.Char> watchlist_uuid,
    ffi.Pointer<ffi.Char> video_uuid,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_watchlist_remove_video(
      watchlist_uuid,
      video_uuid,
      token,
    );
  }

  late final _alexandria_watchlist_remove_videoPtr =
      _lookup<
        ffi.NativeFunction<
          WatchlistJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_watchlist_remove_video');
  late final _alexandria_watchlist_remove_video =
      _alexandria_watchlist_remove_videoPtr
          .asFunction<
            WatchlistJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Update watch progress (UC-23 / FR-WL-04, FR-WL-05).
  ///
  /// `watchlist_uuid` and `video_uuid` are the watchlist's and video's public
  /// UUIDs (NUL-terminated strings). `json_body` is the JSON body HTTP would
  /// send (`state`, optional `currentEpisode`/`totalEpisodes`). On success
  /// `json` carries the updated `WatchProgress` — byte-for-byte the same shape
  /// HTTP returns from `PATCH /v1/watchlists/{uuid}/items/{videoUuid}`
  /// (parity, FR-FC-24 / NFR-09). `token` is the bearer auth token.
  WatchlistJsonResult alexandria_watchlist_update_progress(
    ffi.Pointer<ffi.Char> watchlist_uuid,
    ffi.Pointer<ffi.Char> video_uuid,
    ffi.Pointer<ffi.Char> json_body,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_watchlist_update_progress(
      watchlist_uuid,
      video_uuid,
      json_body,
      token,
    );
  }

  late final _alexandria_watchlist_update_progressPtr =
      _lookup<
        ffi.NativeFunction<
          WatchlistJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_watchlist_update_progress');
  late final _alexandria_watchlist_update_progress =
      _alexandria_watchlist_update_progressPtr
          .asFunction<
            WatchlistJsonResult Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
            )
          >();

  /// Browse watchlists and their items' watch progress (UC-21 / FR-WL-08).
  ///
  /// `json_filters` is the JSON filter HTTP would build from its query string
  /// (`watchlistUuid`); an empty string or `null` means every watchlist. On
  /// success `json` carries a JSON array of `WatchlistWithProgress` — byte-for-
  /// byte the same shape HTTP returns from `GET /v1/watchlists` (parity,
  /// FR-FC-24 / NFR-09). `token` is the bearer auth token.
  WatchlistJsonResult alexandria_watchlists_list(
    ffi.Pointer<ffi.Char> json_filters,
    ffi.Pointer<ffi.Char> token,
  ) {
    return _alexandria_watchlists_list(json_filters, token);
  }

  late final _alexandria_watchlists_listPtr =
      _lookup<
        ffi.NativeFunction<
          WatchlistJsonResult Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('alexandria_watchlists_list');
  late final _alexandria_watchlists_list = _alexandria_watchlists_listPtr
      .asFunction<
        WatchlistJsonResult Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();
}

const int AUTH_ERR_CONFIG = 8;

const int AUTH_ERR_CONFLICT = 10;

const int AUTH_ERR_INVALID_INPUT = 1;

const int AUTH_ERR_INVALID_STATE = 5;

const int AUTH_ERR_NOT_INITIALIZED = 3;

const int AUTH_ERR_OTHER = 9;

const int AUTH_ERR_UNAUTHORIZED = 2;

const int AUTH_OK = 0;

/// Result of `alexandria_auth_local_login` / `alexandria_auth_local_set_credentials`
/// (UC-34/UC-35). On success `status` is `AUTH_OK` and `json` is a
/// NUL-terminated JSON string of the `LocalLoginResult` /
/// `LocalCredentialsResult` body — byte-for-byte the same shape HTTP
/// returns from the matching `/v1/auth/local/*` endpoint (FR-FC-24 /
/// NFR-09). On failure `json` is NULL and `status` carries the mapped
/// error code. The caller must free `json` with `alexandria_free_string`.
final class AuthJsonResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<AuthJsonResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<AuthJsonResult>()
    ..ref.status = status
    ..ref.json = json;
}

const int BOOKMARK_ERR_INVALID_INPUT = 1;

const int BOOKMARK_ERR_INVALID_STATE = 5;

const int BOOKMARK_ERR_NOT_FOUND = 4;

const int BOOKMARK_ERR_NOT_INITIALIZED = 3;

const int BOOKMARK_ERR_OTHER = 9;

const int BOOKMARK_ERR_UNAUTHORIZED = 2;

const int BOOKMARK_OK = 0;

/// Result of `alexandria_bookmark_create` (UC-15). On success `status` is
/// `BOOKMARK_OK` and `json` is a NUL-terminated JSON string of the `Bookmark`
/// body — byte-for-byte the same shape HTTP returns from `POST
/// /v1/bookmarks` (FR-FC-24 / NFR-09). On failure `json` is NULL and `status`
/// carries the mapped error code. The caller must free `json` with
/// `alexandria_free_string`.
final class BookmarkJsonResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<BookmarkJsonResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<BookmarkJsonResult>()
    ..ref.status = status
    ..ref.json = json;
}

const int COLLECTION_ERR_INVALID_INPUT = 1;

const int COLLECTION_ERR_INVALID_STATE = 5;

const int COLLECTION_ERR_NOT_FOUND = 4;

const int COLLECTION_ERR_NOT_INITIALIZED = 3;

const int COLLECTION_ERR_OTHER = 9;

const int COLLECTION_ERR_UNAUTHORIZED = 2;

const int COLLECTION_OK = 0;

/// Result of `alexandria_collection_create` (UC-10). On success `status` is
/// `COLLECTION_OK` and `json` is a NUL-terminated JSON string of the
/// `Collection` body — byte-for-byte the same shape HTTP returns from
/// `POST /v1/collections` (FR-FC-24 / NFR-09). On failure `json` is NULL and
/// `status` carries the mapped error code. The caller must free `json` with
/// `alexandria_free_string`.
final class CollectionJsonResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<CollectionJsonResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<CollectionJsonResult>()
    ..ref.status = status
    ..ref.json = json;
}

const int FILE_ERR_DISK = 6;

const int FILE_ERR_INTEGRITY = 7;

const int FILE_ERR_INVALID_INPUT = 1;

const int FILE_ERR_INVALID_STATE = 5;

const int FILE_ERR_NOT_FOUND = 4;

const int FILE_ERR_NOT_INITIALIZED = 3;

const int FILE_ERR_OTHER = 9;

const int FILE_ERR_UNAUTHORIZED = 2;

const int FILE_OK = 0;

/// Result of `alexandria_files_list` and `alexandria_file_get_by_uuid` (UC-03).
/// On success `status` is `FILE_OK` and `json` is a NUL-terminated JSON string
/// — byte-for-byte the same shape HTTP returns from `GET /v1/files` (a JSON
/// array of `File` records) or `GET /v1/files/{uuid}` (a `FileView` object),
/// so the FFI and HTTP surfaces agree modulo key ordering (parity, FR-FC-24 /
/// NFR-09). On failure `json` is NULL and `status` carries the mapped error
/// code. The caller must free `json` with `alexandria_free_string`.
final class FileJsonResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<FileJsonResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<FileJsonResult>()
    ..ref.status = status
    ..ref.json = json;
}

/// Result of `alexandria_file_edit_metadata` (UC-04). On success `status` is
/// `FILE_OK` and `json` is a NUL-terminated JSON string of the `FileMetadata`
/// body — byte-for-byte the same shape HTTP returns from
/// `PATCH /v1/files/{uuid}/metadata` (FR-FC-24 / NFR-09). On failure `json`
/// is NULL and `status` carries the mapped error code. The caller must free
/// `json` with `alexandria_free_string`.
final class FileMetadataResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<FileMetadataResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<FileMetadataResult>()
    ..ref.status = status
    ..ref.json = json;
}

const int INDEX_ERR_INVALID_INPUT = 1;

const int INDEX_ERR_NOT_INITIALIZED = 3;

const int INDEX_ERR_OTHER = 4;

const int INDEX_ERR_UNAUTHORIZED = 2;

const int INDEX_OK = 0;

/// Result of starting an index run. `run_id` is a NUL-terminated UUID string
/// on success (empty on failure).
final class IndexStartResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  @ffi.Array.multi([37])
  external ffi.Array<ffi.Char> run_id;
}

/// JSON result for the playback functions. `json` is NULL on error and
/// `status` carries the mapped code. The caller must free `json` with
/// `alexandria_free_string`.
final class PlaybackJsonResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<PlaybackJsonResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<PlaybackJsonResult>()
    ..ref.status = status
    ..ref.json = json;
}

const int READING_LIST_ERR_INVALID_INPUT = 1;

const int READING_LIST_ERR_INVALID_STATE = 5;

const int READING_LIST_ERR_NOT_FOUND = 4;

const int READING_LIST_ERR_NOT_INITIALIZED = 3;

const int READING_LIST_ERR_OTHER = 9;

const int READING_LIST_ERR_UNAUTHORIZED = 2;

const int READING_LIST_OK = 0;

/// Result of `alexandria_reading_list_create` (UC-26). On success `status`
/// is `READING_LIST_OK` and `json` is a NUL-terminated JSON string of the
/// `ReadingList` body — byte-for-byte the same shape HTTP returns from
/// `POST /v1/reading-lists` (FR-FC-24 / NFR-09). On failure `json` is NULL
/// and `status` carries the mapped error code. The caller must free `json`
/// with `alexandria_free_string`.
final class ReadingListJsonResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<ReadingListJsonResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<ReadingListJsonResult>()
    ..ref.status = status
    ..ref.json = json;
}

/// Result of `alexandria_index_run_status_json` (UC-42). On success `status`
/// is `RUN_OK` and `json` is a NUL-terminated JSON string of the `CatalogRun`
/// body — byte-for-byte the same shape HTTP returns from
/// `GET /v1/index/runs/{runId}` (FR-FC-24 / NFR-09). On failure `json` is
/// NULL and `status` carries the mapped error code. The caller must free
/// `json` with `alexandria_free_string`.
final class RunJsonResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<RunJsonResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<RunJsonResult>()
    ..ref.status = status
    ..ref.json = json;
}

const int WATCHLIST_ERR_INVALID_INPUT = 1;

const int WATCHLIST_ERR_INVALID_STATE = 5;

const int WATCHLIST_ERR_NOT_FOUND = 4;

const int WATCHLIST_ERR_NOT_INITIALIZED = 3;

const int WATCHLIST_ERR_OTHER = 9;

const int WATCHLIST_ERR_UNAUTHORIZED = 2;

const int WATCHLIST_OK = 0;

/// Result of `alexandria_watchlist_create` (UC-20). On success `status` is
/// `WATCHLIST_OK` and `json` is a NUL-terminated JSON string of the
/// `Watchlist` body — byte-for-byte the same shape HTTP returns from `POST
/// /v1/watchlists` (FR-FC-24 / NFR-09). On failure `json` is NULL and
/// `status` carries the mapped error code. The caller must free `json` with
/// `alexandria_free_string`.
final class WatchlistJsonResult extends ffi.Struct {
  @ffi.Int()
  external int status;

  external ffi.Pointer<ffi.Char> json;

  static ffi.Pointer<WatchlistJsonResult> $allocate(
    ffi.Allocator $allocator, {
    required int status,
    required ffi.Pointer<ffi.Char> json,
  }) => $allocator<WatchlistJsonResult>()
    ..ref.status = status
    ..ref.json = json;
}
